#!/usr/bin/env bash
# PreToolUse hook for Bash. Enforces CLAUDE.md "Git" and
# "Never without explicit human authorization".
# Exit 2 = block the call and show stderr to Claude.
set -uo pipefail

command=$(jq -r '.tool_input.command // ""')
[ -z "$command" ] && exit 0

deny() { echo "BLOCKED by .claude/hooks/guard-bash.sh — $1" >&2; exit 2; }

# symbolic-ref (not rev-parse) so the guard also works on an unborn branch,
# where rev-parse --abbrev-ref HEAD returns the literal "HEAD".
branch=$(git -C "${CLAUDE_PROJECT_DIR:-.}" symbolic-ref --short -q HEAD 2>/dev/null || echo "")

# Never work directly on main or develop.
if [ "$branch" = "main" ] || [ "$branch" = "master" ] || [ "$branch" = "develop" ]; then
  if grep -qE '(^|[;&|[:space:]])git[[:space:]]+(commit|push|merge|rebase)([[:space:]]|$)' <<<"$command"; then
    deny "CLAUDE.md forbids working directly on '$branch'. Create a branch from develop first:
  git switch -c <feat|fix|refactor|docs|test|chore>/<ticket>-<description> origin/develop"
  fi
fi

# Force push. After 'git rebase origin/develop', a feature branch is pushed
# with --force-with-lease (docs/workflow.md). Anything else needs explicit
# human authorization.
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+push\b' <<<"$command"; then
  if grep -qE '[[:space:]](--force([[:space:]]|=|$)|-[a-zA-Z]*f[a-zA-Z]*([[:space:]]|$)|\+[^[:space:]]+)' <<<"$command"; then
    deny "only 'git push --force-with-lease' on your own feature branch is allowed (CLAUDE.md). Plain --force, -f and +refspec need explicit human authorization."
  fi
  if grep -qE -- '--force-with-lease' <<<"$command"; then
    if grep -qE '(^|[[:space:]:])(main|master|develop)([[:space:]]|$)' <<<"$command"; then
      deny "force pushing to main or develop is never allowed."
    fi
  fi
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+reset\b.*--hard' <<<"$command"; then
  deny "destructive reset requires explicit human authorization (CLAUDE.md). Prefer 'git stash' or 'git restore'."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+branch[[:space:]]+(-D|--delete[[:space:]]+--force)' <<<"$command"; then
  deny "deleting an unmerged branch requires explicit human authorization (CLAUDE.md)."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+(clean\b.*-[a-z]*f|filter-branch|filter-repo)' <<<"$command"; then
  deny "this rewrites or deletes work irreversibly and requires explicit human authorization (CLAUDE.md)."
fi

# Generated Unity directories are never version controlled or edited.
if grep -qE '>[[:space:]]*"?(\./)?(Library|Temp|Obj|Logs|Build|Builds)/' <<<"$command"; then
  deny "Library/, Temp/, Obj/, Logs/ and build outputs are generated by Unity — never write into them."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+add\b.*(^|[[:space:]])"?(\./)?(Library|Temp|Obj|Logs|Build|Builds)/' <<<"$command"; then
  deny "generated Unity directories must not be committed. They are already in .gitignore."
fi

exit 0
