#!/usr/bin/env bash
# PreToolUse hook for Write/Edit. Protects generated Unity directories
# and .meta files (asset GUIDs are contracts — CLAUDE.md / unity-serialization).
set -uo pipefail

path=$(jq -r '.tool_input.file_path // ""')
[ -z "$path" ] && exit 0

deny() { echo "BLOCKED by .claude/hooks/guard-write.sh — $1" >&2; exit 2; }

case "$path" in
  */Library/*|*/Temp/*|*/Obj/*|*/Logs/*|*/Build/*|*/Builds/*|Library/*|Temp/*|Obj/*|Logs/*|Build/*|Builds/*)
    deny "'$path' is inside a generated Unity directory. Unity owns these — never write into them." ;;
esac

case "$path" in
  *.meta)
    deny "'$path' is a Unity .meta file. GUIDs are contracts and .meta files are generated by the Unity Editor.
Editing one by hand can break every reference to that asset. If this is genuinely required, ask the developer to do it in Unity." ;;
esac

exit 0
