#!/usr/bin/env bash
# PreToolUse hook for Write/Edit. Protects generated Unity directories
# and .meta files (asset GUIDs are contracts — CLAUDE.md / unity-serialization).
set -uo pipefail

# Fail closed: without jq this hook cannot read the tool input, and an empty
# input would otherwise be waved through. On Windows, winget puts jq in its
# Links folder, which a process started before the install does not have on
# PATH yet — look there before giving up.
if ! command -v jq >/dev/null 2>&1 && [ -n "${LOCALAPPDATA:-}" ]; then
  PATH="$PATH:$(cygpath -u "$LOCALAPPDATA" 2>/dev/null || echo "$LOCALAPPDATA")/Microsoft/WinGet/Links"
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "BLOCKED by $(basename "$0") — jq is not installed, so this guard cannot read the command.
Install it (Windows: winget install jqlang.jq · macOS: brew install jq · Debian/Ubuntu: apt install jq), then restart Claude Code." >&2
  exit 2
fi

path=$(jq -r '.tool_input.file_path // ""')
[ -z "$path" ] && exit 0

deny() { echo "BLOCKED by .claude/hooks/guard-write.sh — $1" >&2; exit 2; }

case "$path" in
  */Library/*|*/Temp/*|*/Obj/*|*/Logs/*|*/Build/*|*/Builds/*|Library/*|Temp/*|Obj/*|Logs/*|Build/*|Builds/*)
    deny "'$path' is inside a generated Unity directory. Unity owns these — never write into them." ;;
esac

case "$path" in
  *.meta)
    deny "'$path' is a Unity .meta file. GUIDs are contracts and .meta files are generated by the Unity Editor.
Editing one by hand can break every reference to that asset. If this is genuinely required, ask the developer to do it in Unity." ;;
esac

exit 0
