#!/usr/bin/env bash
# PreToolUse hook for Bash. Enforces CLAUDE.md "Git" and
# "Never without explicit human authorization".
# Exit 2 = block the call and show stderr to Claude.
set -uo pipefail

# Fail closed: without jq this hook cannot read the tool input, and an empty
# input would otherwise be waved through. On Windows, winget puts jq in its
# Links folder, which a process started before the install does not have on
# PATH yet — look there before giving up.
if ! command -v jq >/dev/null 2>&1 && [ -n "${LOCALAPPDATA:-}" ]; then
  PATH="$PATH:$(cygpath -u "$LOCALAPPDATA" 2>/dev/null || echo "$LOCALAPPDATA")/Microsoft/WinGet/Links"
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "BLOCKED by $(basename "$0") — jq is not installed, so this guard cannot read the command.
Install it (Windows: winget install jqlang.jq · macOS: brew install jq · Debian/Ubuntu: apt install jq), then restart Claude Code." >&2
  exit 2
fi

command=$(jq -r '.tool_input.command // ""')
[ -z "$command" ] && exit 0

deny() { echo "BLOCKED by .claude/hooks/guard-bash.sh — $1" >&2; exit 2; }

# symbolic-ref (not rev-parse) so the guard also works on an unborn branch,
# where rev-parse --abbrev-ref HEAD returns the literal "HEAD".
branch=$(git -C "${CLAUDE_PROJECT_DIR:-.}" symbolic-ref --short -q HEAD 2>/dev/null || echo "")

# Never work directly on main.
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  if grep -qE '(^|[;&|[:space:]])git[[:space:]]+(commit|push|merge|rebase)([[:space:]]|$)' <<<"$command"; then
    deny "CLAUDE.md forbids working directly on '$branch'. Create a branch first:
  git checkout -b <feat|fix|refactor|docs|test|chore>/<ticket>-<description>"
  fi
fi

# Destructive git operations need explicit human authorization.
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+push\b.*--force' <<<"$command"; then
  deny "force push requires explicit human authorization (CLAUDE.md). Ask the developer."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+reset\b.*--hard' <<<"$command"; then
  deny "destructive reset requires explicit human authorization (CLAUDE.md). Prefer 'git stash' or 'git restore'."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+branch[[:space:]]+(-D|--delete[[:space:]]+--force)' <<<"$command"; then
  deny "deleting an unmerged branch requires explicit human authorization (CLAUDE.md)."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+(clean\b.*-[a-z]*f|filter-branch|filter-repo)' <<<"$command"; then
  deny "this rewrites or deletes work irreversibly and requires explicit human authorization (CLAUDE.md)."
fi

# Generated Unity directories are never version controlled or edited.
if grep -qE '>[[:space:]]*"?(\./)?(Library|Temp|Obj|Logs|Build|Builds)/' <<<"$command"; then
  deny "Library/, Temp/, Obj/, Logs/ and build outputs are generated by Unity — never write into them."
fi
if grep -qE '(^|[;&|[:space:]])git[[:space:]]+add\b.*(^|[[:space:]])"?(\./)?(Library|Temp|Obj|Logs|Build|Builds)/' <<<"$command"; then
  deny "generated Unity directories must not be committed. They are already in .gitignore."
fi

exit 0
