#!/usr/bin/env bash
# Enforces CLAUDE.md "Git": Conventional Commits, and no AI attribution.
#
# Usage: scripts/check-commit-message.sh <file containing the message>
set -uo pipefail

msg_file="${1:?usage: check-commit-message.sh <file>}"
subject=$(grep -vE '^\s*#' "$msg_file" | sed '/^\s*$/d' | head -1)

# Merge, revert and fixup subjects are generated by git itself.
if grep -qE '^(Merge|Revert|fixup!|squash!)' <<<"$subject"; then
  exit 0
fi

types='feat|fix|refactor|test|docs|chore|perf|build|ci'

if ! grep -qE "^($types)(\([a-z0-9._-]+\))?!?: .+" <<<"$subject"; then
  cat >&2 <<MSG
Conventional Commits required (CLAUDE.md).

  Got:      $subject
  Expected: type(scope): description
  Types:    feat fix refactor test docs chore perf build ci

  Examples: feat(movement): add player sprint
            fix(physics): prevent player clipping through ramps
            docs(adr): document movement architecture
MSG
  exit 1
fi

if [ ${#subject} -gt 72 ]; then
  echo "Subject is ${#subject} chars, keep it under 72: $subject" >&2
  exit 1
fi

if grep -qiE '(co-authored-by:.*(claude|anthropic|copilot|gpt|cursor)|generated with .*claude|🤖)' "$msg_file"; then
  cat >&2 <<'MSG'
CLAUDE.md forbids crediting Claude or any AI as author.
Remove the Co-authored-by / "Generated with" / 🤖 line and use the developer's Git identity.
MSG
  exit 1
fi

exit 0
